In [1]:
import pandas as pd
import numpy as np
import re

# negative altitudes
# regular expressions for numbers (x.0 !!)

#np.where()

In [596]:
random_numbers=pd.read_csv('data4.txt',header=None,nrows=1)
bingo_tables=pd.read_csv('data4.txt',header=None,delimiter='\s+',skiprows=1)

In [597]:
random_numbers.shape,bingo_tables.shape

((1, 100), (500, 5))

In [598]:
bingo_tables=np.array(bingo_tables)
bingo_tables=bingo_tables.reshape(100,5,5)
bingo_tables_long=np.ndarray.flatten(bingo_tables)

In [599]:
random_numbers=np.array(random_numbers)
random_numbers=random_numbers.reshape(100)
random_numbers=pd.Series(random_numbers)

In [377]:
np.sum([[1,2],[3,4]],axis=1)

array([3, 7])

In [401]:
test=[[1,2,,4,5],[5,6,7,8,9]]

90

In [600]:
bingo_tables=np.array(bingo_tables)
bingo_tables=bingo_tables.reshape(100,5,5)
bingo_tables_long=np.ndarray.flatten(bingo_tables)

tensor=np.array([np.zeros(5*5*100)])
record_tensor=tensor.reshape(100,5,5)
record_tensor_long=np.ndarray.flatten(record_tensor)
stop=[]

for draw in random_numbers:
    for j in range(0,2500):
            if draw == bingo_tables_long[j]:
                record_tensor_long[j]=1
    for k in range(0,100):
        if 5 in np.sum(record_tensor_long.reshape(100,5,5)[k],axis=1) or 5 in np.sum(record_tensor_long.reshape(100,5,5)[k],axis=0):
            #print('tensor:',k,'draw:',draw)
            #print(record_tensor_long.reshape(100,5,5)[k])
            winner_record=record_tensor_long.reshape(100,5,5)[k]
            winner_table=bingo_tables_long.reshape(100,5,5)[k]
            stop=1       
    if stop==1:
        for j in range(0,5):
            for k in range(0,5):
                if winner_record[k,j]==1:
                    winner_table[k,j]=0
        print('result for first winner:',sum(winner_table).sum()*draw)
        break
      

result for first winner: 35711


In [586]:
bingo_tables=np.array(bingo_tables)
bingo_tables=bingo_tables.reshape(100,5,5)
bingo_tables_long=np.ndarray.flatten(bingo_tables)

tensor=np.array([np.zeros(5*5*100)])
record_tensor=tensor.reshape(100,5,5)
record_tensor_long=np.ndarray.flatten(record_tensor)
stop=[]
order_of_winners=np.array(np.zeros(100))
score_list=[]

counter=0

for p,draw in enumerate(random_numbers):
    for j in range(0,2500-counter*25):
            if draw == bingo_tables_long[j]:
                record_tensor_long[j]=1
    for k in range(0,100):
        if 5 in np.sum(record_tensor_long.reshape(100-counter,5,5)[k],axis=1) or 5 in np.sum(record_tensor_long.reshape(100-counter,5,5)[k],axis=0):
            #print('tensor:',k,'draw:',draw)
            #print(record_tensor_long.reshape(100,5,5)[k])
            winner_record=record_tensor_long.reshape(100,5,5)[k]
            winner_table=bingo_tables_long.reshape(100,5,5)[k]
            counter=1
            bingo_tables=np.delete(bingo_tables,k,0)
            record_tenser=np.delete(record_tenser,k,0)
            record_tensor_long=np.ndarray.flatten(record_tensor)
            
            order_of_winners[k]=1
            stop=1       
   
    if stop==1:
        for j in range(0,5):
            for k in range(0,5):
                if winner_record[k,j]==1: 
                    winner_table[k,j]=0
        score=sum(winner_table).sum()*draw 
        score_list.append(score)
        stop=0
        
        print('result for first winner:',score)

      

result for first winner: 35711
result for first winner: 45640
result for first winner: 35045
result for first winner: 72535
result for first winner: 77425
result for first winner: 85360
result for first winner: 53680
result for first winner: 67760
result for first winner: 47488
result for first winner: 27047
result for first winner: 21199
result for first winner: 7310
result for first winner: 51508
result for first winner: 16952
result for first winner: 33252
result for first winner: 28992
result for first winner: 2400
result for first winner: 41280
result for first winner: 32021
result for first winner: 26158
result for first winner: 35178
result for first winner: 40590
result for first winner: 25707
result for first winner: 36982
result for first winner: 20295
result for first winner: 31570
result for first winner: 4961
result for first winner: 6314
result for first winner: 5863
result for first winner: 22550
result for first winner: 30668
result for first winner: 42394
result for fi

In [572]:
order_of_winners=np.array(np.zeros(100))

In [ ]:
score

In [594]:
bingo_tables=np.delete(bingo_tables,0,0)
bingo_tables

array([[[33, 57, 76, 73, 26],
        [ 6, 71, 35, 39, 85],
        [54, 77, 36, 14, 87],
        [66, 79,  8, 64, 32],
        [ 2, 84, 98, 34, 13]],

       [[43, 51, 16, 95, 59],
        [22, 53,  6, 49, 94],
        [32, 72, 46, 23, 37],
        [40, 85, 39, 45, 74],
        [87, 62, 69, 98,  0]],

       [[84,  5, 73, 32, 23],
        [40, 64, 98, 27,  8],
        [80, 71,  1, 31, 69],
        [46, 42,  7,  4, 70],
        [88, 90, 48, 33, 29]],

       ...,

       [[15, 53, 20, 35, 14],
        [24, 25, 63, 85, 79],
        [65, 96,  2, 60, 50],
        [72, 10, 77, 12, 92],
        [32, 94, 95, 16, 71]],

       [[78, 52, 55, 20, 40],
        [33, 66, 81, 48, 18],
        [32, 69, 13,  5, 84],
        [23, 67, 68, 61, 34],
        [11, 63,  4, 93, 65]],

       [[51, 89, 37, 46, 29],
        [69, 56, 71,  9, 91],
        [28, 54,  7, 16, 31],
        [67,  5, 97, 42, 43],
        [98, 32, 65, 34, 30]]])

In [592]:
bingo_tables[49]

array([[20, 61, 63, 82, 53],
       [86, 11, 55, 10, 85],
       [ 5, 37, 65, 21, 54],
       [89, 75, 59, 73, 48],
       [41, 50, 29, 71, 93]])

In [376]:
bingo_tables[51][1,0]

86

In [477]:
result=np.array([[1,0,1,0,0],[1,1,0,0,0],[1,1,1,1,1],[0,1,0,0,0],[0,0,0,0,0]])
result[1,1]

1

In [549]:
sum(bingo_tables[49]).sum()*41

50553