In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
with open("data11.txt", "r") as file:
    data = str(file.read())

In [3]:
input_data=data.split('\n')

In [4]:
def splitting(words):
    return [int(char) for char in words]

In [5]:
data=[]
for i in input_data:
    a=splitting(i)
    data.append(a)

In [6]:
data=np.array(data)

In [7]:
data.shape

(10, 10)

In [8]:
data

array([[5, 6, 5, 1, 3, 4, 1, 4, 5, 2],
       [1, 3, 8, 1, 5, 4, 1, 2, 5, 2],
       [1, 8, 7, 8, 4, 3, 5, 2, 2, 4],
       [6, 8, 1, 4, 8, 3, 1, 5, 3, 5],
       [3, 8, 8, 3, 5, 4, 7, 3, 8, 3],
       [6, 4, 7, 3, 5, 4, 8, 4, 6, 4],
       [1, 8, 8, 5, 8, 3, 3, 6, 5, 8],
       [3, 7, 3, 2, 5, 8, 4, 7, 5, 2],
       [1, 8, 8, 1, 5, 4, 6, 1, 2, 8],
       [5, 1, 2, 1, 7, 1, 7, 7, 7, 6]])

In [169]:
data_new=data+1

In [175]:
data_new

array([[6, 7, 6, 2, 4, 5, 2, 5, 6, 3],
       [2, 4, 9, 2, 6, 5, 2, 3, 6, 3],
       [2, 9, 8, 9, 5, 4, 6, 3, 3, 5],
       [7, 9, 2, 5, 9, 4, 2, 6, 4, 6],
       [4, 9, 9, 4, 6, 5, 8, 4, 9, 4],
       [7, 5, 8, 4, 6, 5, 9, 5, 7, 5],
       [2, 9, 9, 6, 9, 4, 4, 7, 6, 9],
       [4, 8, 4, 3, 6, 9, 5, 8, 6, 3],
       [2, 9, 9, 2, 6, 5, 7, 2, 3, 9],
       [6, 2, 3, 2, 8, 2, 8, 8, 8, 7]])

In [60]:
def flash(data):
    flash_count=0
    for row in range(0,len(data)):
        for el in range(0,len(data)):
            if data[row][el] ==0:
                flash_count+=1
    return flash_count

In [13]:
def step(data):
    for row in range(0,len(data)):
        for el in range(0,len(data)):
            if data[row][el]==9:
                data[row][el]=0
            else:
                data[row][el]+=1

In [170]:
def flash_marker(data):
    flash_marker=np.array(np.zeros(data.shape[0]*data.shape[1])).reshape([data.shape[0],data.shape[1]])
    for row in range(0,len(data)):
        for el in range(0,len(data)):
            if data[row][el]==0:
                flash_marker[row][el]+=1
    return flash_marker

In [231]:
def propagate(data):
    flash_marker=np.array(np.zeros(data.shape[0]*data.shape[1])).reshape([data.shape[0],data.shape[1]])
    for row in range(0,len(data)):
        for el in range(0,len(data)):
            if data[row][el]==0 and flash_marker[row][el]!=1:
                if inner_element(row,el,data):
                    data[row-1][el]+=1
                    data[row-1][el+1]+=1
                    data[row][el+1]+=1
                    data[row+1][el+1]+=1
                    data[row+1][el]+=1
                    data[row+1][el-1]+=1
                    data[row][el-1]+=1
                    data[row-1][el-1]+=1
                elif left(row,el,data):
                    if up(row,el,data):
                        data[row][el+1]+=1
                        data[row+1][el+1]+=1
                        data[row+1][el]+=1
                    elif down(row,el,data):
                        data[row-1][el]+=1
                        data[row-1][el+1]+=1
                        data[row][el+1]+=1       
                elif right(row,el,data):
                    if up(row,el,data):
                        data[row+1][el]+=1
                        data[row+1][el-1]+=1
                        data[row][el-1]+=1
                    elif down(row,el,data):
                        data[row][el-1]+=1
                        data[row-1][el-1]+=1
                        data[row-1][el]+=1  
            flash_marker[row][el]+=1
    return flash_marker

In [232]:
test=np.array([[1,2,3,4,5,6],[4,5,6,7,8,9],[7,8,9,3,2,6],[7,8,9,4,1,7],[7,8,9,8,9,2],[7,8,9,4,6,8]])

In [233]:
step(test)

In [242]:
propagate(test)    

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

<function __main__.flash_marker(data)>

In [216]:
flash(test)

4

In [243]:
test

array([[ 2,  3,  4,  5,  6,  7],
       [ 5, 12, 13, 14,  9,  0],
       [ 8, 15,  0, 10,  3,  7],
       [ 8, 21, 12, 23,  8, 14],
       [ 8, 15,  0, 21,  0,  9],
       [ 8, 15,  6, 17, 13, 15]])

In [67]:
def inner_element(row,el,data):
    if row > 0 and row < (data.shape[0]-1) and el > 0 and el < (data.shape[1]-1):
        return True
    else:
        return False

In [68]:
def left(row,el,data):
    if el == 0:
        return True
    else:
        return False

In [69]:
def right(row,el,data):
    if el ==(data.shape[1]-1):
        return True
    else:
        return False

In [70]:
def up(row,el,data):
    if row == 0:
        return True
    else:
        return False

In [71]:
def down(row,el,data):
    if row ==(data.shape[0]-1):
        return True
    else:
        return False

In [80]:
down(5,5,test)

True